### ISSUE TITLE
Support for Java enum classes?

### ISSUE THREAD

**Issue by JonathanLennox** [gershnik/SimpleJNI#1]
Java enum classes seem like they'd be fairly straightforward to support, but they're not currently supported in jnigen, and awkward in smjni.  How hard would this be to add?

**Comment by gershnik** [comment]
Good question! I've been away from Java world for quite a bit so will need to take a look at how these look from JNI side and what would be a good way to expose them. Do you have a mental picture of what a desired C++ side interface could be?

Thank you!

**Comment by gershnik** [comment]
Ok, at the first blush it *seems* that adding enums to jnigen shouldn't be too hard. On the C++ side enum members will be exposed simply as static fields with their original names. I'll try to add it to jnigen and see how it goes.

**Comment by gershnik** [comment]
And after digging through the code turns out that non-handling of enums is a bug, not a feature. 🙂 Caused by not handling an enum member of all things! Fix should be out in a couple of days.

**Comment by JonathanLennox** [comment]
Since the values of the enum fields are static final members, I think it should be possible to actually get the enum object itself (presumably with a global ref) rather than just the field that holds it.

**Comment by gershnik** [comment]
Ok this functionality is now available in release 3.9. It should appear on Maven central shortly. You use it just like regular static fields, e.g.

```java
@ExposeToNative
enum AnEnum {
   @CalledByNative FIRST,
   @CalledByNative SECOND
}
```

```cpp
auto cls = java_classes::get<AnEnum>();
auto firstObj = cls.get_FIRST(env);
```

The reference you get back is a local ref - as always with JNI. Making a global ref is always a C++ code choice as it has non-trivial implications. (the total amount of global references may be limited on some JVMs and they preclude GC).

Hope it works for your use case!

**Comment by gershnik** [comment]
Is this resolved now? 🙂

Thank you!

**Comment by JonathanLennox** [comment]
Yes, looks good!

I'm able to get the global refs myself based on the generated classes, and it's pretty easy.

Thank you!
